# The URL the site will be built for
base_url = "https://tobb10001.github.io/masters-in-iceland"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

default_language = "de"

theme = "tabi"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
render_emoji = true

[extra]
# Tabi
archive_reverse = true
skin = "red"
menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    # { name = "projects", url = "projects", trailing_slash = true },
    # { name = "about", url = "about", trailing_slash = true },
    # { name = "github", url = "https://github.com/welpo/tabi", trailing_slash = false },
]

[languages.de]
title = "Master in Island 🇮🇸"
taxonomies = [{ name = "tags", feed = true }]

[languages.en]
title = "Masters in Iceland 🇮🇸"
taxonomies = [{ name = "tags", feed = true}]
